version: "3"

services:
  urlshortserver:
    build:
      context: ./.devcontainer/
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: url_shortener_dev
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: url_shortener_dev
      PGPORT: 5432
    command: ./entrypoint.sh
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: url_shortener_dev
      PGPORT: 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
